### ISSUE TITLE
提示假消息有点多

### ISSUE THREAD

**Issue by dark748001** [n0thing2speak/oracle_arm#1]
![image](https://user-images.githubusercontent.com/64937100/139806344-c70c9f71-b0cf-4f56-bb81-9b512f892f7c.png)
![image](https://user-images.githubusercontent.com/64937100/139806440-2b4be3f5-ac5e-4cba-9620-fc62af04cb1c.png)

**Comment by n0thing2speak** [comment]
确认一下资源是到上限吗？如果到上限了跟开通成功的提示是一样的

**Comment by n0thing2speak** [comment]
代码全部重构了，解决误报问题，欢迎使用
