### ISSUE TITLE
请问这是什么问题呢

### ISSUE THREAD

**Issue by sea0302** [n0thing2speak/oracle_arm#2]
![image](https://user-images.githubusercontent.com/32325218/140632526-229c0317-b16d-469d-80ab-97cc58e1469d.png)

**Comment by n0thing2speak** [comment]
资源达到上限了，应该是 没有免费配额了，你调低一点配置，或者去看看你那里占用了配额

**Comment by sea0302** [comment]
谢谢

test1234455 ***@***.***> 于2021年11月7日周日 下午3:13写道：
